
#line 3 "olib.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 37
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 68
#define YY_END_OF_BUFFER 69
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[327] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   69,   68,   67,   68,
       68,   66,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,    9,   68,   68,   68,   10,   68,
       12,   68,   68,   68,   68,   68,   68,   49,   68,   68,
       68,   68,   68,   68,   68,   61,   63,   63,   64,   63,
       65,   65,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   32,   68,   68,   30,

       29,   32,   68,   68,   68,   68,   67,   37,   68,   37,
       68,    0,    0,    1,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    9,    0,    0,   10,
       12,    0,    0,   47,    0,    0,   49,    0,    0,    0,
       53,   56,   57,    0,    0,    0,    0,    0,   62,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   30,   29,   30,    0,   36,
        0,    0,   37,    0,    1,    0,    0,    5,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    4,    0,
        8,    0,    0,   48,   47,    0,    0,   51,   50,   60,

       54,   58,   55,    0,   59,   23,   26,    0,    0,    0,
        0,   33,    0,    0,    0,    0,    0,    0,    0,    0,
       31,   35,   36,    0,    7,    0,    0,   18,   13,    0,
        0,    0,    0,   21,    0,    0,    0,    0,    0,    3,
        0,    0,   47,    0,    0,    0,    0,   27,   24,   28,
        0,   44,    0,    0,    0,   39,    0,    0,    0,    0,
       36,    0,    0,    0,    0,    0,    0,   19,    0,   17,
        0,   16,    0,    0,    0,   47,    0,    0,   52,    0,
        0,    0,    0,   45,    0,   43,    0,   42,    0,   36,
        0,    2,    0,    0,    0,    0,    0,    0,   22,   25,

        0,    0,    0,   38,    0,   20,    0,    0,   14,    0,
        0,   34,    0,   46,    0,    0,   40,    0,   15,    0,
        0,    0,   41,    6,   11,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    1,    1,    1,    5,    1,
        1,    1,    6,    1,    6,    7,    8,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    1,    1,    1,
        1,    1,    1,    1,   10,   11,   12,   13,   14,   15,
       16,   17,   18,    1,   19,   20,    1,   21,   22,   23,
        1,   24,   25,   26,   27,   28,   29,   30,   31,   32,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,   33,   34,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,   35,    1,   36,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[37] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[359] =
    {   0,
        0,   34,    3,    5,   12,   68,   24,   73,  107,  141,
       26,  175,   82,   84,  209,  491,   29,   48,   63,   92,
       97,   99,  102,  104,  243,    6,  119,  276,  303,  337,
      123,  368,  127,  133,  146,  150,  493,  495,  495,  468,
      455,  495,    0,  466,  480,   34,  467,  469,    4,    2,
      472,  464,    0,  475,  474,    0,  468,  472,  471,  470,
      469,  453,    0,  467,  453,  460,  464,  463,  451,  448,
        4,  106,   14,  452,  382,  495,  495,  495,  402,  359,
      495,  495,    0,  369,  373,  372,  371,  373,  365,  361,
       93,  363,  365,  364,  367,  366,  495,    0,   71,  369,

      105,  495,    0,  368,  362,  372,  371,  495,  128,  495,
        0,  357,  334,  495,  364,  356,  358,  342,  344,  351,
      343,  341,  331,  348,  346,  353,  348,  351,  340,  345,
      344,  334,  346,  341,  328,  336,  338,  326,  315,  315,
      495,  495,  495,  310,  310,  310,  311,  300,  495,  326,
      318,  305,  308,  306,  296,  312,  312,  299,  301,  308,
      300,  298,  288,  305,  311,  306,  131,  305,  308,  302,
      295,  300,  495,  138,  298,  295,  284,  495,  295,  294,
      156,  283,  266,  290,  272,  275,  261,  259,  495,  281,
      495,  269,  269,  495,  272,  252,  251,  495,  495,  495,

      495,  495,  495,  252,  495,  495,  495,  263,  254,  259,
      246,  495,  268,  258,  240,  264,  246,  251,  238,  236,
      495,  495,  252,  234,  495,  241,  254,  495,  495,  157,
      236,  240,  249,  495,  248,  247,  246,  225,  240,  495,
      217,  230,  230,  224,  215,  210,  215,  495,  495,  495,
      230,  495,  210,  215,  225,  495,  223,  222,  221,  201,
      211,  197,  188,  214,  202,  191,  211,  495,  210,  495,
      206,  495,  184,  193,  182,  495,  181,  180,  495,  188,
      186,  174,  194,  495,  193,  495,  191,  495,  169,  495,
      168,  495,  188,  164,  186,  167,  160,  157,  495,  495,

      179,  153,  172,  495,  170,  495,  169,  168,  495,  158,
      159,  495,  164,  495,  160,  158,  495,  153,  495,  132,
      114,   86,  495,  495,  495,  495,  396,  399,  402,  405,
       80,   71,   62,   54,   41,   40,    3,  408,  411,    0,
      414,  417,  420,  423,  426,  429,  432,  435,  438,  441,
      444,  447,  450,  453,  456,  459,  462,  465
    } ;

static yyconst flex_int16_t yy_def[359] =
    {   0,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327,  327,   15,  327,  327,  328,  328,
      327,  327,  327,  327,  327,   25,  327,   25,  327,  327,
      327,   12,  329,  329,  327,  327,  326,  326,  326,  326,
      330,  326,  331,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  332,  326,  326,  333,  326,  326,  326,  326,
      326,  326,  334,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  330,
      326,  326,  335,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  336,  326,  326,

      326,  326,  337,  326,  326,  338,  338,  326,  339,  326,
      340,  326,  330,  326,  331,  326,  341,  326,  326,  326,
      326,  326,  326,  326,  326,  332,  326,  333,  326,  326,
      326,  326,  334,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  335,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  336,  326,  326,  326,  337,  326,
      326,  338,  326,  339,  338,  340,  326,  326,  342,  341,
      341,  326,  326,  343,  326,  326,  326,  326,  326,  344,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,

      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  345,  326,  326,  346,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  342,  326,  326,  341,
      326,  326,  343,  326,  347,  348,  349,  326,  344,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      345,  326,  326,  326,  346,  326,  350,  351,  352,  326,
      326,  326,  326,  341,  326,  326,  347,  326,  348,  326,
      349,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  350,  326,  351,  326,  352,  326,  326,  326,
      326,  326,  353,  326,  354,  326,  326,  326,  326,  326,

      355,  326,  356,  326,  353,  326,  357,  354,  326,  326,
      326,  326,  355,  326,  358,  356,  326,  357,  326,  326,
      326,  358,  326,  326,  326,    0,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326
    } ;

static yyconst flex_int16_t yy_nxt[532] =
    {   0,
      176,   39,   39,  169,   39,   39,   39,   42,   42,   53,
      117,  140,  117,   39,   39,  123,   52,   54,   52,   89,
       55,  122,   40,  145,  141,   39,   39,   39,   39,   58,
       39,   39,   59,   76,   41,   39,   42,   41,   43,   41,
      165,  150,  146,   44,   45,   46,   41,   47,   48,   39,
       42,  118,   76,   49,  133,  119,   40,   45,   41,   50,
       41,   51,  128,   41,   78,   39,   38,   79,   41,   39,
       42,  126,   56,   54,   39,   42,   55,  166,   58,  167,
      115,   59,   41,   39,   39,   39,   42,   67,  323,   67,
       68,   57,   68,   78,   42,   38,   79,   80,   39,   39,

       39,   42,   41,   39,   81,   39,   82,   41,   39,   39,
      158,  166,   60,  167,  159,   61,   41,  142,   41,  143,
       39,   39,   62,   83,   39,   39,   80,  103,  107,  108,
      173,   41,  144,   41,  107,  110,   41,  166,   41,  167,
      173,   41,   39,   42,  325,  324,   60,   39,   39,   61,
      111,   39,   42,   41,  111,  319,   62,   41,  229,  229,
      317,  109,  323,  175,  230,  264,  314,  109,  321,  320,
      309,  319,  306,  175,  317,   41,   39,   42,  315,   63,
       41,  314,  312,  311,   41,   64,   65,  310,  309,  307,
      306,  304,  303,  288,   64,  286,  284,  302,   64,  301,

       64,  300,   66,  299,  298,  297,  296,  295,  272,   41,
       39,   39,  270,  268,  294,  293,  229,  292,  291,  290,
       69,   70,  289,  288,  286,  284,   71,  256,  282,  281,
       72,   73,  252,   74,  280,  279,  278,  277,  276,  275,
      274,   75,  240,   41,   39,   39,  273,   83,  272,  270,
      268,  234,   84,  266,   85,  265,  228,   86,  263,  262,
      261,  260,   87,  259,  258,  257,  256,  254,   88,  253,
      252,  250,  249,  248,  247,  246,  245,   41,   42,  244,
      243,  242,  241,  240,  238,   90,  237,   91,  236,   92,
       93,  235,  234,  232,  231,   94,  229,  228,  226,  225,

      173,   95,  173,   96,   39,   97,  224,   98,   99,  100,
      223,  101,  222,  168,  168,  221,  220,  219,  218,  217,
      216,  215,  214,  213,  212,  211,  210,  209,  208,  207,
      206,  205,  204,  203,  202,  201,  200,   41,   39,  102,
      199,   98,   99,  100,  198,  101,  137,  197,  196,  195,
      194,  193,  131,  130,  192,  191,  127,  190,  189,  188,
      187,  186,  185,  184,  183,  182,  181,  179,  178,  114,
      177,   41,  103,  173,  173,  171,  170,  168,  104,  164,
      163,  162,  161,  160,  157,  156,  155,  104,  154,  153,
      152,  104,  151,  104,  114,  105,   38,   38,   38,   77,

       77,   77,  106,  106,  106,  113,  149,  113,  172,  172,
      172,  174,  174,  174,  180,  148,  180,  227,  227,  227,
      233,  233,  233,  239,  239,  239,  251,  251,  251,  255,
      255,  255,  267,  267,  267,  269,  269,  269,  271,  271,
      271,  283,  283,  283,  285,  285,  285,  287,  287,  287,
      305,  305,  305,  308,  308,  308,  313,  313,  313,  316,
      316,  316,  318,  318,  318,  322,  322,  322,  147,  139,
      138,  137,  137,  136,  135,  134,  132,  131,  131,  130,
      130,  129,  127,  127,  125,  124,  121,  120,  117,  116,
      114,  112,  326,   42,   37,  326,  326,  326,  326,  326,

      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326
    } ;

static yyconst flex_int16_t yy_chk[532] =
    {   0,
      340,    1,    1,  337,    3,    3,    4,    4,   26,    4,
       50,   71,   49,    5,    5,   50,    3,    5,    4,   26,
        5,   49,    1,   73,   71,    7,    7,   11,   11,    7,
       17,   17,    7,   17,    1,    2,    2,    3,    2,    4,
      336,  335,   73,    2,    2,    2,    5,    2,    2,   18,
       18,   46,   18,    2,  334,   46,    2,    2,    7,    2,
       11,    2,  333,   17,   19,   19,   19,   19,    2,    6,
        6,  332,    6,    6,    8,    8,    6,   99,    8,   99,
      331,    8,   18,   13,   13,   14,   14,   13,  322,   14,
       13,    6,   14,   20,   20,   20,   20,   19,   21,   21,

       22,   22,    6,   23,   23,   24,   24,    8,    9,    9,
       91,  101,    9,  101,   91,    9,   13,   72,   14,   72,
       27,   27,    9,   27,   31,   31,   20,   31,   33,   33,
      109,   21,   72,   22,   34,   34,   23,  167,   24,  167,
      174,    9,   10,   10,  321,  320,   10,   35,   35,   10,
       35,   36,   36,   27,   36,  318,   10,   31,  181,  230,
      316,   33,  315,  109,  181,  230,  313,   34,  311,  310,
      308,  307,  305,  174,  303,   10,   12,   12,  302,   12,
       35,  301,  298,  297,   36,   12,   12,  296,  295,  294,
      293,  291,  289,  287,   12,  285,  283,  282,   12,  281,

       12,  280,   12,  278,  277,  275,  274,  273,  271,   12,
       15,   15,  269,  267,  266,  265,  264,  263,  262,  261,
       15,   15,  260,  259,  258,  257,   15,  255,  254,  253,
       15,   15,  251,   15,  247,  246,  245,  244,  243,  242,
      241,   15,  239,   15,   25,   25,  238,   25,  237,  236,
      235,  233,   25,  232,   25,  231,  227,   25,  226,  224,
      223,  220,   25,  219,  218,  217,  216,  215,   25,  214,
      213,  211,  210,  209,  208,  204,  197,   25,   28,  196,
      195,  193,  192,  190,  188,   28,  187,   28,  186,   28,
       28,  185,  184,  183,  182,   28,  180,  179,  177,  176,

      175,   28,  172,   28,   29,   29,  171,   29,   29,   29,
      170,   29,  169,  168,  166,  165,  164,  163,  162,  161,
      160,  159,  158,  157,  156,  155,  154,  153,  152,  151,
      150,  148,  147,  146,  145,  144,  140,   29,   30,   30,
      139,   30,   30,   30,  138,   30,  137,  136,  135,  134,
      133,  132,  131,  130,  129,  128,  127,  126,  125,  124,
      123,  122,  121,  120,  119,  118,  117,  116,  115,  113,
      112,   30,   32,  107,  106,  105,  104,  100,   32,   96,
       95,   94,   93,   92,   90,   89,   88,   32,   87,   86,
       85,   32,   84,   32,   80,   32,  327,  327,  327,  328,

      328,  328,  329,  329,  329,  330,   79,  330,  338,  338,
      338,  339,  339,  339,  341,   75,  341,  342,  342,  342,
      343,  343,  343,  344,  344,  344,  345,  345,  345,  346,
      346,  346,  347,  347,  347,  348,  348,  348,  349,  349,
      349,  350,  350,  350,  351,  351,  351,  352,  352,  352,
      353,  353,  353,  354,  354,  354,  355,  355,  355,  356,
      356,  356,  357,  357,  357,  358,  358,  358,   74,   70,
       69,   68,   67,   66,   65,   64,   62,   61,   60,   59,
       58,   57,   55,   54,   52,   51,   48,   47,   45,   44,
       41,   40,   37,   16,  326,  326,  326,  326,  326,  326,

      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "olib.l"
#line 2 "olib.l"
/*  $Id$

    olib.lex - Orcad to gEDA lib converter
    Copyright (C) 2002 Mario Pascucci <m.pas@libero.it>

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
    or
    visit the URL http://www.fsf.org/

*/

#include <unistd.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <ctype.h>
#include <limits.h>
#include <math.h>

/* gEDA file version: change NEW version as soon as available */
#define EDA_VERSION_OLD   "20020209"
#define EDA_VERSION_NEW	  "20020825"


/* defines for flags and types */
#define PIN_DOTFLAG	0x0001
#define PIN_SHORTFLAG	0x0002
#define PIN_CLKFLAG	0x0004

#define PIN_TYPE_IO	1
#define PIN_TYPE_IN	2
#define PIN_TYPE_OUT	3
#define PIN_TYPE_PWR	4
#define	PIN_TYPE_PAS	5
#define PIN_TYPE_OC	6
#define PIN_TYPE_HIZ	7
#define PIN_TYPE_OE	8


#ifndef GCC_VERSION
#define GCC_VERSION (__GNUC__ * 1000 + __GNUC_MINOR__)
#endif /* GCC_VERSION */

#if GCC_VERSION > 2007
#define ATTRIBUTE_UNUSED __attribute__((unused)) 
#else
#define ATTRIBUTE_UNUSED
#endif 

static const ATTRIBUTE_UNUSED char *mp_name = "OrCAD to gEDA lib converter";
static const ATTRIBUTE_UNUSED char *mp_license = "Copyright (c) 2002 Mario Pascucci <m.pas@libero.it>";

static char fnsym[512];	    /* gEDA symbol file name */
static FILE *fsym;	    /* FILE* to gEDA symbol file */
static int aliascount = 0;    /* alias count */
static char part_aliases[200][50];     /* store for aliases of part */
static char sym_prefix[50];	/* prefix for .sym file */

/* gEDA symbol file version */
static char sym_version[10];
static int use_old_version;	  /* flag for old format */

/* pin name options */
static int pin_name_hidden;

static char buff[512];

static int sizex,sizey,partspp;	  /* size and number of part per package */

static int pincount;	    /* pin definitions found until now */

struct pin_def {	/* pin definition struct */
  char	pos;	  /* position: L,T,R,B */
  short	num;	  /* number in side, 0 mean virtual pin */
  short	pin;	  /* real pin number */
  short	flags;	  /* DOT, CLK and SHORT flags */
  short	type;	  /* I/O, IN, OUT, PWR, PASS, OC */
  char  name[50]; /* simbolic name of pin */
};


/* REFERENCE handling */
static char ref_str[20];


/* VECTOR handling */
static int vector_count;	/* number of vector found */

struct vector_def {
  char	type;		/* line, arc, circle, box */
  float p[12];		/* parameters for element drawing */
  char *str;		/* string for "TEXT" statement */
};

static int paramcount;	/* vector param number count */

static struct vector_def part_vectors[100];   /* draw list */

static int vector_found;


/* type of pin */
static char *pintypestr[] = {
  "???",
  "I/O",
  "IN",
  "OUT",
  "PWR",
  "PAS",
  "OC",
  "hiZ",
  "OE"
};


static char *edapintype[] = {
  "???",
  "io",
  "in",
  "out",
  "pwr",
  "pas",
  "oc",
  "tri",
  "oe"
};


 /* pin definition database */
static struct pin_def pinlist[200];


/* generic counter */
static int ii;



/* strip filename-aware chars from part name,
    leave only '.' '-' or '_' and changes space
    in '_' */
char *strip_invalid(char *str)
{
  char *p;

  p = buff;
  while (*str)
  {
    if (isalnum((int) *str) || strchr("-_. ",*str))
    {
      if (*str == ' ')
	*p = '_';
      else
	*p = *str;
      p++;
    }
    str++;
  }
  *p = 0;
  return buff;
}


/* trim leading and trailing ' in ident */
char *strip_quotes(char *str)
{
  char *p;

  p = buff;
  str++;
  while (*str != '\'')
  {
    *p = *str;
    p++;
    str++;
  }
  *p = 0;
  return buff;
}



/* symbol write function in gEDA .sym format */
#include "geda_sym_format.h"


/* decimal integer */
/* floating point decimal, like 123.234 */
/* string name, like 'abcd' */
/* comment, like { comment } */
/* pin identifier, example T3 L12 R3 .... */
 


#line 886 "olib.c"

#define INITIAL 0
#define wait_END 1
#define wait_sizex 2
#define wait_sizey 3
#define wait_parts 4
#define pin_list 5
#define pinrealnum 6
#define pindata 7
#define waitnamestart 8
#define in_name 9
#define waitnameend 10
#define waitpinend 11
#define vector_list 12
#define vector_ignore 13
#define param_list 14
#define convert 15
#define convert_ignore_pin 16
#define reference 17

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 225 "olib.l"



  /*******************************************
  handling of:
  PREFIX
  'prefix1'
  'prefix2'
  ...
  ...
  END
  *******************************************/


#line 1103 "olib.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 327 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 495 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 239 "olib.l"
{
  /* ignore comments */
  fprintf(stderr,"Ignore comment: %s\n",yytext);
 }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 245 "olib.l"
{
  /* shortcuts for parts name: ignored */
  fprintf(stderr,"Found PREFIX\n");
  BEGIN(wait_END);
 }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 252 "olib.l"
{
  fprintf(stderr,"Shorthand found, ignored\n");
  /* ignore shortcut list */
 }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 258 "olib.l"
{
  /* founds shortcut list end */
  fprintf(stderr,"Found END for shorthands\n");
  BEGIN(INITIAL);
 }
	YY_BREAK


  /*******************************************
  handling of:
  'IDENT'
  'IDENT'
  ...
  *******************************************/

case 5:
YY_RULE_SETUP
#line 274 "olib.l"
{
  /* founds first part identifier */
  strcpy(part_aliases[0],strip_invalid(yytext));
  snprintf(fnsym,511,"%s-%s-1.sym",sym_prefix,part_aliases[0]);
  fprintf(stderr,"New part name: %s (%s)\n",part_aliases[0],yytext);
  fprintf(stderr,"New .sym name: %s\n",fnsym);
  BEGIN(wait_sizex);
  aliascount = 1;
  pincount = 0;
  vector_found = 0;
  ref_str[0] = 'U';
  ref_str[1] = 0;
 }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 289 "olib.l"
{
  /* REFERENCE statement found */
  BEGIN(reference);
 }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 295 "olib.l"
{
  /* get an IDENT, i.e. reference id */
  strcpy(ref_str,strip_quotes(yytext));
  fprintf(stderr,"REFERENCE: %s\n",yytext);
  BEGIN(wait_sizex);
 }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 303 "olib.l"
{
  /* found an alias for the part name 
      store alias for future use */
  fprintf(stderr,"Found an alias: %s\n",yytext);
  strcpy(part_aliases[aliascount], strip_invalid(yytext));
  aliascount++;
 }
	YY_BREAK

  /*******************************************
  handling of:
  {X Size =} x      {Y Size =} y      {Parts per Package =} n
  *******************************************/

case 9:
YY_RULE_SETUP
#line 319 "olib.l"
{
  /* trovata la dimansione X */
  sizex = atoi(yytext);
  fprintf(stderr,"Found X size: %d (%s)\n",sizex,yytext);
  BEGIN(wait_sizey);
 }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 327 "olib.l"
{
  /* trovata la dimansione y */
  sizey = atoi(yytext);
  fprintf(stderr,"Found Y size: %d (%s)\n",sizey,yytext);
  BEGIN(wait_parts);
 }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 335 "olib.l"
{
  /* found a PGA component, unsupported */
  fprintf(stderr,"Found a GRIDARRAY: unsupported\n");
  BEGIN(INITIAL);
 }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 342 "olib.l"
{
  /* trovato il parts-per-package */
  /* per ora supportato solo 1 part-per-package */
  partspp = atoi(yytext);
  if (partspp > 1)
  {
    fprintf(stderr,"Found parts per package > 1\n");
    BEGIN(INITIAL);
  }
  else
  {
    fprintf(stderr,"Found parts per package: %d (%s)\n",partspp,yytext);
    BEGIN(pin_list);
    /* size of symbol body */
    sizex = sizex * PIN_SPACE;
    sizey = sizey * PIN_SPACE;
  }
 }
	YY_BREAK
case 13:
/* rule 13 can match eol */
#line 363 "olib.l"
case 14:
/* rule 14 can match eol */
#line 364 "olib.l"
case 15:
/* rule 15 can match eol */
#line 365 "olib.l"
case 16:
/* rule 16 can match eol */
#line 366 "olib.l"
case 17:
/* rule 17 can match eol */
#line 367 "olib.l"
case 18:
/* rule 18 can match eol */
#line 368 "olib.l"
case 19:
/* rule 19 can match eol */
#line 369 "olib.l"
case 20:
/* rule 20 can match eol */
#line 370 "olib.l"
case 21:
/* rule 21 can match eol */
YY_RULE_SETUP
#line 370 "olib.l"
{
  /* ignored */
  fprintf(stderr,"Ignored: %s",yytext);
 }
	YY_BREAK

  /*******************************************
  handling of:
  VECTOR 'IDENT'  (unsupported)
  or
  VECTOR
  LINE x y x1 y1
  ARC x y dxs dys dxe dye r
  CIRCLE x y r
  FILL x y    (unsupported)
  TEXT x y size 'text'	(partially supported)
  END
  *******************************************/

case 22:
YY_RULE_SETUP
#line 391 "olib.l"
{
  /* components isn't a simple "box", but it's drawed */
  BEGIN(vector_list);
  vector_count = 0;
  vector_found = -1;
  fprintf(stderr,"Found: VECTOR\n");
 }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 400 "olib.l"
{
  /* the component shape is identical to a previous one 
      unsupported at the moment */
  BEGIN(pin_list);
  fprintf(stderr,"Found unsupported: VECTOR 'IDENT'\n");
 }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 408 "olib.l"
{
  /* found LINE vector statement */
  part_vectors[vector_count].type = 'L';
  BEGIN(param_list);
  paramcount = 0;
  fprintf(stderr,"Found: LINE params:");
 }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 417 "olib.l"
{
  /* found CIRCLE vector statement */
  part_vectors[vector_count].type = 'V';
  BEGIN(param_list);
  paramcount = 0;
  fprintf(stderr,"Found: CIRCLE params:");
 }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 426 "olib.l"
{
  /* found ARC vector statement */
  part_vectors[vector_count].type = 'A';
  BEGIN(param_list);
  paramcount = 0;
  fprintf(stderr,"Found: ARC params:");
 }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 435 "olib.l"
{
  /* found FILL vector statement */
  /* no counterpart in gEDA */
  part_vectors[vector_count].type = 'f';
  BEGIN(param_list);
  paramcount = 0;
  fprintf(stderr,"Found unsupported: FILL params:");
 }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 445 "olib.l"
{
  /* found ARC vector statement */
  part_vectors[vector_count].type = 'T';
  BEGIN(param_list);
  paramcount = 0;
  fprintf(stderr,"Found: TEXT params:");
 }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 454 "olib.l"
{
  /* found a param */
  part_vectors[vector_count].p[paramcount] = (float) atof(yytext);
  paramcount++;
  BEGIN(param_list);
  fprintf(stderr," %s",yytext);
 }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 463 "olib.l"
{
  /* found a param */
  part_vectors[vector_count].p[paramcount] = (float) atof(yytext);
  paramcount++;
  BEGIN(param_list);
  fprintf(stderr," %s",yytext);
 }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 472 "olib.l"
{
  /* found a string */
  if (part_vectors[vector_count].type == 'T')
    part_vectors[vector_count].str = strdup(strip_quotes(yytext));
  else
    fprintf(stderr,"Text param found in non text VECTOR instr: %s\n",yytext);
  paramcount++;
  BEGIN(param_list);
  fprintf(stderr," %s",yytext);
 }
	YY_BREAK
case 32:
/* rule 32 can match eol */
YY_RULE_SETUP
#line 484 "olib.l"
{
  /* end of params */
  fprintf(stderr,"\n");
  switch (part_vectors[vector_count].type)
  {
    case 'L':
      /* line */
      if (paramcount != 4)
      {
	fprintf(stderr,"LINE: wrong parameters number: %d\n",paramcount);
	BEGIN(vector_list);
      }
      break;
    case 'V':
      /* circle */
      if (paramcount != 3)
      {
	fprintf(stderr,"CIRCLE: wrong parameters number: %d\n",paramcount);
	BEGIN(vector_list);
      }
      break;
    case 'A':
      /* arc */
      if (paramcount != 7)
      {
	fprintf(stderr,"ARC: wrong parameters number: %d\n",paramcount);
	BEGIN(vector_list);
      }
      break;
    case 'f':
      /* fill (ignored) */
      if (paramcount != 2)
      {
	fprintf(stderr,"FILL: wrong parameters number: %d\n",paramcount);
	BEGIN(vector_list);
      }
      break;
    case 'T':
      /* text */
      if (paramcount != 4)
      {
	fprintf(stderr,"TEXT: wrong parameters number: %d\n",paramcount);
	BEGIN(vector_list);
      }
      break;
  }
  vector_count++;
  BEGIN(vector_list);
 }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 535 "olib.l"
{
  /* end of vector list */
  BEGIN(pin_list);
  fprintf(stderr,"Found: END of VECTOR list\n");
 }
	YY_BREAK

  /*******************************************
  handling of:
  CONVERT 'IDENT'
  or
  CONVERT
  pin_def
  pin_def
  ...
  *******************************************/

case 34:
YY_RULE_SETUP
#line 554 "olib.l"
{
  /* alternate part drawing */
  /* unsupported */
  BEGIN(convert);
 }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 561 "olib.l"
{
  /* CONVERT 'part' unsupported */
  BEGIN(pin_list);
 }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 567 "olib.l"
{
  /* ignore PIN list in CONVERT */
  BEGIN(convert_ignore_pin);
 }
	YY_BREAK
case 37:
/* rule 37 can match eol */
YY_RULE_SETUP
#line 573 "olib.l"
{
  /* ignore line */
  BEGIN(convert);
 }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 579 "olib.l"
{
  /* found VECTOR list in CONVERT */
  if (vector_found)
    BEGIN(vector_ignore);
  else
  {
    BEGIN(vector_list);
    vector_count = 0;
    vector_found = -1;
  }
 }
	YY_BREAK
case 39:
/* rule 39 can match eol */
YY_RULE_SETUP
#line 592 "olib.l"
{
  /* end of ignore */
  BEGIN(pin_list);
 }
	YY_BREAK
case 40:
/* rule 40 can match eol */
#line 597 "olib.l"
case 41:
/* rule 41 can match eol */
#line 598 "olib.l"
case 42:
/* rule 42 can match eol */
#line 599 "olib.l"
case 43:
/* rule 43 can match eol */
#line 600 "olib.l"
case 44:
/* rule 44 can match eol */
#line 601 "olib.l"
case 45:
/* rule 45 can match eol */
#line 602 "olib.l"
case 46:
/* rule 46 can match eol */
YY_RULE_SETUP
#line 602 "olib.l"
{
  /* ignored */
  fprintf(stderr,"Ignored VECTOR: %s",yytext);
 }
	YY_BREAK

  /*******************************************
  handling of:
  pin_def
  pin_def
  ...
  *******************************************/

case 47:
YY_RULE_SETUP
#line 617 "olib.l"
{
  /* trovato un pin */
  pinlist[pincount].pos = yytext[0];    /* pin side */
  pinlist[pincount].num = atoi(yytext+1);	/* gets pin number */
  pinlist[pincount].flags = 0;
  pinlist[pincount].type = 0;
  fprintf(stderr,"Found pin ID: %c-%d (%s)\n",pinlist[pincount].pos,pinlist[pincount].num,yytext);
  if (partspp == 0)   /* handling of parts without pin number */
  {
    /* assign number to a unnumbered pin from the pin count */
    pinlist[pincount].pin = pincount + 1;
    BEGIN(pindata);
  }
  else
    BEGIN(pinrealnum);
 }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 635 "olib.l"
{
  /* found a part name after pinlist, this mean that part definition ends,
      and starts a new part definition */
  fprintf(stderr,"Writing down new symbol: %s pin: %d  vectors: %d\n",part_aliases[0],pincount,vector_count);
  write_sym();	    /* write the .sym gEDA symbol definition */
  /* restore initial condition */
  ref_str[0] = 'U';
  ref_str[1] = 0;
  pincount = 0;
  aliascount = 1;
  vector_found = 0;
  vector_count = 0;
  strcpy(part_aliases[0],strip_invalid(yytext));
  snprintf(fnsym,511,"%s-%s-1.sym",sym_prefix,part_aliases[0]);
  fprintf(stderr,"New part name: %s (%s)\n",part_aliases[0],yytext);
  fprintf(stderr,"New .sym name: %s\n",fnsym);
  BEGIN(wait_sizex);
 }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 656 "olib.l"
{
  /* reads real pin number */
  pinlist[pincount].pin = atoi(yytext);
  fprintf(stderr,"Found pin num: %d (%s)\n",pinlist[pincount].pin,yytext);
  BEGIN(pindata);
 }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 664 "olib.l"
{
  /* DOT flag found, boolean negate */
  pinlist[pincount].flags |= PIN_DOTFLAG;
  fprintf(stderr,"Found DOT flag\n");
 }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 671 "olib.l"
{
  /* CLK flag found, clock input */
  pinlist[pincount].flags |= PIN_CLKFLAG;
  fprintf(stderr,"Found CLK flag\n");
 }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 678 "olib.l"
{
  /* SHORT flag found, short terminal */
  pinlist[pincount].flags |= PIN_SHORTFLAG;
  fprintf(stderr,"Found SHORT flag\n");
 }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 685 "olib.l"
{
  /* pin type IN */
  pinlist[pincount].type = PIN_TYPE_IN;
  BEGIN(waitnamestart);
  fprintf(stderr,"Pin type IN\n");
 }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 693 "olib.l"
{
  /* pin type OUT */
  pinlist[pincount].type = PIN_TYPE_OUT;
  BEGIN(waitnamestart);
  fprintf(stderr,"Pin type OUT\n");
 }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 701 "olib.l"
{
  /* pin type PWR */
  pinlist[pincount].type = PIN_TYPE_PWR;
  BEGIN(waitnamestart);
  fprintf(stderr,"Pin type PWR\n");
 }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 709 "olib.l"
{
  /* pin type OC */
  pinlist[pincount].type = PIN_TYPE_OC;
  BEGIN(waitnamestart);
  fprintf(stderr,"Pin type OC\n");
 }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 717 "olib.l"
{
  /* pin type OE */
  pinlist[pincount].type = PIN_TYPE_OE;
  BEGIN(waitnamestart);
  fprintf(stderr,"Pin type OE\n");
 }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 725 "olib.l"
{
  /* pin type PAS */
  pinlist[pincount].type = PIN_TYPE_PAS;
  BEGIN(waitnamestart);
  fprintf(stderr,"Pin type PAS\n");
 }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 733 "olib.l"
{
  /* pin type hiZ */
  pinlist[pincount].type = PIN_TYPE_HIZ;
  BEGIN(waitnamestart);
  fprintf(stderr,"Pin type hiZ\n");
 }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 741 "olib.l"
{
  /* pin type I/O */
  pinlist[pincount].type = PIN_TYPE_IO;
  BEGIN(waitnamestart);
  fprintf(stderr,"Pin type I/O\n");
 }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 749 "olib.l"
{
  /* found initial quote */
  ii = 0;
  BEGIN(in_name);
 }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 756 "olib.l"
{
  /* found a ' in pin name */
  pinlist[pincount].name[ii++] = '\'';
 }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 762 "olib.l"
{
  /* get a char from the pin symbolic name */
  pinlist[pincount].name[ii++] = *yytext;
 }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 768 "olib.l"
{
  /* all ok, waiting for new pin definition */
  pinlist[pincount].name[ii] = 0;
  fprintf(stderr,"Pin label: %s\n",pinlist[pincount].name);
  BEGIN(waitpinend);
 }
	YY_BREAK
case 65:
/* rule 65 can match eol */
YY_RULE_SETUP
#line 776 "olib.l"
{
  /* ok, found a newline, pin definition ends */
  fprintf(stderr,"Pin: %c%d %d %x %s %s\n",pinlist[pincount].pos,pinlist[pincount].num,
    pinlist[pincount].pin, pinlist[pincount].flags, pintypestr[pinlist[pincount].type],
    pinlist[pincount].name);
  pincount++;
  BEGIN(pin_list);
 }
	YY_BREAK

  /* 
   * we don't need to use <*> to match any state, we just don't
   * specify a state
   */

case 66:
/* rule 66 can match eol */
YY_RULE_SETUP
#line 793 "olib.l"
{ /* empty lines ignored */ }
	YY_BREAK
case 67:
/* rule 67 can match eol */
YY_RULE_SETUP
#line 796 "olib.l"
{ /* ignored, the \r char is for "DOS" ASCII files */ }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 802 "olib.l"
ECHO;
	YY_BREAK
#line 1891 "olib.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(wait_END):
case YY_STATE_EOF(wait_sizex):
case YY_STATE_EOF(wait_sizey):
case YY_STATE_EOF(wait_parts):
case YY_STATE_EOF(pin_list):
case YY_STATE_EOF(pinrealnum):
case YY_STATE_EOF(pindata):
case YY_STATE_EOF(waitnamestart):
case YY_STATE_EOF(in_name):
case YY_STATE_EOF(waitnameend):
case YY_STATE_EOF(waitpinend):
case YY_STATE_EOF(vector_list):
case YY_STATE_EOF(vector_ignore):
case YY_STATE_EOF(param_list):
case YY_STATE_EOF(convert):
case YY_STATE_EOF(convert_ignore_pin):
case YY_STATE_EOF(reference):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 327 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 327 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 326);

		return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 802 "olib.l"




void usage(void)
{
  fprintf(stderr,"Usage:\n");
  fprintf(stderr,"\tolib [options] libname prefix\n");
  fprintf(stderr,"\nWhere:\n\tlibname is the path to OrCAD(TM) library to convert\n");
  fprintf(stderr,"\tprefix is the prefix for the .sym files extracted\n");
  fprintf(stderr,"Options are:\n\t-h\tprint this help and exit\n");
  fprintf(stderr,"\t-o\tuse old format (v 20020209) for .sym file\n");
  fprintf(stderr,"\t\telse use 'v 20020825' as version string in .sym file\n");
  fprintf(stderr,"\t-n\thides pin name if symbol is VECTOR drawed\n");
}

int yywrap()
{
  /* found a part name after pinlist, this mean that part definition ends,
      and starts a new part definition */
  fprintf(stderr,"Writing down new symbol: %s pin: %d  vectors: %d\n",part_aliases[0],pincount,vector_count);      
  write_sym();	    /* write the .sym gEDA symbol definition */
  /* restore initial condition */
  fprintf(stderr,"End of lib file\n");

  return 1;
}


int main (int argc, char *argv[])
{

  FILE	*flib;
  char	fnlib[PATH_MAX];
  int	i;

  strcpy(sym_version,EDA_VERSION_NEW);	  /* handle new gEDA version by default */
  use_old_version = 0;	      /* old version flag */
  pin_name_hidden = 0;	      /* hides pin name on VECTOR drawed symbols */
  opterr = 0;	/* do NOT print default error message for getopt */
  do
  {
    i = getopt(argc,argv,"hon");
    switch (i)
    {
      case 'h':
	usage();
	exit(0);
      case 'o':
	strcpy(sym_version,EDA_VERSION_OLD);
	fprintf(stderr,"Use old (%s) format.\n",sym_version);
	use_old_version = -1;
	break;
      case 'n':
	pin_name_hidden = -1;
	break;
      case '?':
	fprintf(stderr,"Unknown or illegal option :%c\n",(char)optopt);
	usage();
	exit(1);
      case ':':
	fprintf(stderr,"Parameter wrong for option: %c\n",(char)optopt);
	usage();
	exit(1);
    }
  }
  while (i != -1);
  if ((argc - optind) != 2)
  {
    fprintf(stderr,"Library name and prefix are mandatory.\n");
    usage();
    return 1;
  }
  strcpy(fnlib,argv[optind]);
  if (!(flib = fopen(fnlib,"r")))
  {
    perror("lib file");
    return 1;
  }
  strcpy(sym_prefix,argv[optind+1]);
  yyin = flib;
  yylex();
  fclose(flib);
  return 0;  
}



