#!/bin/sh
set -e

OLDCONF=/etc/gEDA/system-gafrc
if [ "$1" = purge ]; then
	# geda-symbols used to own /etc/gEDA/system-gafrc, but now it
	# belongs to libgeda-common. If that package is installed and
	# owns the config file, don't remove it here.
	if ! dpkg-query -f '${Conffiles}\n' -W geda-common | grep -q $OLDCONF ; then
		echo Removing old configuration file $OLDCONF ...
		rm -f $OLDCONF || true
	fi
fi

#DEBHELPER#

